### PR TITLE
Added more Travis build tests

### PR DESCRIPTION
**Pull request by hummeltech**
Added build, test & install on "Debian", "Ubuntu", "CentOS" & "OracleLinux" via Docker

### CODE REVIEW

**Comment by hummeltech** [comment]
WIP

**Comment by hummeltech** [comment]
Some of these are currently failing, they should all pass once #41 gets merged in.

**Comment by hummeltech** [comment]
All passing now after a rebase.
https://app.travis-ci.com/github/jruby/jruby-launcher/builds/232243277

**Comment by headius** [comment]
Nice, thank you! This should help avoid regressing like we did after the last fix (curse you, libc headers!)

**Pull request merged**
